apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"your-react-app","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"your-react-app"}},"template":{"metadata":{"labels":{"app":"your-react-app"}},"spec":{"containers":[{"env":[{"name":"REACT_APP_POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}}],"image":"joberengineering/repo_of_test:testTag","name":"your-react-app-container","ports":[{"containerPort":3000}]}],"imagePullSecrets":[{"name":"my-registry-secret"}]}}}}
  creationTimestamp: "2023-12-30T21:30:34Z"
  generation: 4
  labels:
    k8slens-edit-resource-version: v1
  name: your-react-app
  namespace: default
  resourceVersion: "4545515"
  uid: 5c212dc3-4574-4cde-b5dc-8429220c201a
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: your-react-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: your-react-app
    spec:
      containers:
      - env:
        - name: REACT_APP_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: joberengineering/repo_of_test:testTag
        imagePullPolicy: IfNotPresent
        name: your-react-app-container
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: my-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2023-12-30T21:30:34Z"
    lastUpdateTime: "2023-12-30T21:49:51Z"
    message: ReplicaSet "your-react-app-765cf7cb67" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-03-24T21:54:34Z"
    lastUpdateTime: "2024-03-24T21:54:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3